apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyeglass-aggregator
  labels:
    app: eyeglass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyeglass
  template:
    metadata:
      labels:
        app: eyeglass
    spec:
      containers:
      - name: aggregator
        image: eyeglass.aggregator
        imagePullPolicy: Never
