apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyeglass-deployment
  labels:
    app: eyeglass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eyeglass
  template:
    metadata:
      labels:
        app: eyeglass
    spec:
      containers:
      - name: aggregator
        image: aiacdataengsadev.azurecr.io/eyeglass.aggregator
